tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bat"
brew "exa"
brew "git"
brew "mas"
brew "python@3.9"
cask "alfred"
cask "dropbox"
cask "visual-studio-code"
mas "Xcode", id: 497799835
